set global tabstop 2
set global indentwidth 2
set global scrolloff 4,0

colorscheme gruvbox

map global user y '<a-|>xclip -i -selection clipboard<ret>'
map global user p '!xclip -o -selection clipboard<ret>'

# Indent with only spaces
map global insert <tab> '<a-;><gt>'
map global insert <s-tab> '<a-;><lt>'

hook global BufWritePre .* %{ try %{ execute-keys -draft \%s\h+$<ret>d } }

# Atomic soft tabs
hook global InsertDelete ' ' %{ try %{
  execute-keys -draft 'h<a-h><a-k>\A\h+\z<ret>i<space><esc><lt>'
}}
